language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
script:
- "./gradlew clean assembleDebug testDebug --stacktrace"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - SONATYPE_USERNAME=codemonkey138
  - secure: tKZpuftURf4izANS3oMZYiOCj1z3dcBB1TgRsfqFwvqxFLGFG5HeQzJdpFso6QbYjbMeXqhIhpcgDZITp40GZ2w9tbraj/V48snl1bQq2kLwd5ujalBYnAbLql1DJm2PF91UVn6ikdDvyYdSZAJsnuiI5r4PfywmUoW8/5ha/XqSPPGgVewa5cIY4+weoMdujjfYtTkJC+iHTLPXjh7ejoSSCsMTmq2Kj4lINxKULee1yrBpW8A/QYQWIm+puH3X7k5CuVmDvYb1nB2joVGdKWRcuLsbijx9+v20GSaUkJDIluRQYVU5hG2JhY4G6S4wYfmffEGLp5rYmqZo13CPVjhIJ7CAHy7B1hNusF+vCvj/VERU6meQEeqdMHohfBhdbA8jQfqMWLTzYCoyT9gUBAJu02rikCcVoAEEMEM6clJrzrCuICabVq0qK/1UHyo08FKk5Kg7Jyi4Er9oEXJPUYGz0c1G0Zo7SwEFMI1uPEv2DS6RoAlfLmwwrX4YbM+ZQQnHPqwQ8yyUrKwoHkrDSCNBDrjoWSxtwDSmm6XX78+MXP7HELaNJ+164soWBwt/SR6Ajwb9Kl76VwKClAKhm9B1+SLRpwNkmqrw+/Xm9pXG0TmV0wZj/X52+d3VmXOxUbexYQ08zqlScMd8X+SZ2NVa3ztCNr/IWY4hzYvc94A=
after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B